GET {{local}}/api/client/films

####
POST {{local}}/api/client/user/register
Content-Type: application/json

{
  "name": "Alisher",
  "last_name": "Raximov",
  "email": "ooops2211@gmail.com",
  "password": "alisher2211"
}

#####
POST {{local}}/api/client/user/email/register
Content-Type: application/json

{
  "name": "Alisher",
  "last_name": "Raximov",
  "email": "ooops2211@gmail.com",
  "password": "alisher2211",
  "code": "257"
}

####
POST {{local}}/api/client/login
Content-Type: application/json

{
  "email": "ooops2211@gmail.com",
  "password": "alisher2211"
}

###
POST {{local}}/api/token
Content-Type: application/json

{
  "email": "JohnDoe@gmail.com",
  "name": "John",
  "last_name": "Doe"
}

####
POST {{local}}/api/verifytoken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkpvaG5Eb2VAZ21haWwuY29tIiwibmFtZSI6IkpvaG4iLCJsYXN0X25hbWUiOiJEb2UiLCJpYXQiOjE2MTk0MjgxODcsImV4cCI6MTYxOTQzMDE4N30.x62YNKLcnxS0O6e7QG_rJgrh1FF7Xi9NjpEJqvFZchE",
  "key": "alisher2211"
}
